apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: agentapp-role
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - primaza.io
  resources:
  - servicebindings
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - primaza.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - primaza.io
  resources:
  - serviceclaims
  verbs:
  - get
  - list
  - watch
  - update
